### PR TITLE
utils: detect tracefs or debugfs at runtime

### LINKED ISSUE #797: Fail to find tracing_on file for kernel tracing
It complains as follows:
```
uftrace record -vv --force -K 10 -- dd if=xxx of=/dev/mapper/??? bs=4096
uftrace: checking binary /bin/dd
WARN: Didn't you run 'make install' ?
uftrace: using libmcount.so library for tracing
uftrace: send UFTRACE_MSG_SEND_HDR
kernel: cannot open tracing file: tracing_on: No such file or directory
kernel: failed to reset tracing files
WARN: kernel tracing disabled due to an error
is CONFIG_FUNCTION_GRAPH_TRACER enabled in the kernel?
uftrace: creating 2 thread(s) for recording
uftrace: start writer thread 0
uftrace: start writer thread 1
mcount: initializing mcount library
...
```
However, `tracing_on` file exists.
```
# cat /sys/kernel/tracing/tracing_on
1
```

### PR DESCRIPTION
**Pull request by shpark**
Currently, uftrace interacts with kernel tracing system through
a fixed TRACING_DIR; /sys/kernel/debug/tracing, therefore fails
to trace kernel when a tracefs is mounted at a different location.

This commit introduces runtime detection tracefs or debugfs from
/proc/self/mountinfo (which is newer than /proc</self>/mounts).

Fixes #797 

Signed-off-by: Seonghyun Park <shp4rk@gmail.com>

### CODE REVIEW

**Comment by honggyukim** [comment]
@shpark Thanks for your patch, but is there a reason not to use `setmntent`/`getmntent` as I mentioned at https://github.com/namhyung/uftrace/issues/1471#issuecomment-1179689118? It will make the logic much shorter that the current implementation.

**Comment by honggyukim** [comment]
>  I decided to use /proc/self/mountinfo as it was seemingly more modern.

If we can do the same thing then older interface is more portable than newer ones.

> Plus, I was unsure how universal mntent.h is, like you mentioned Android. I wanted to avoid having something like #ifdef HAVE_MNTENT_H.

I have checked `mntent.h` is also available on Android so I think we can use it.

To make it safer, we can check which one was introduced first between `mntent.h` and `/proc/self/mountinfo`.

@namhyung Do you have any preference on these approaches?

File: utils/mountinfo.c [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+		xasprintf(tracing_dir, "%s", mnt);
+		pr_dbg2("tracefs found at %s\n", mnt);
+		pr_dbg2("TRACING_DIR: %s\n", *tracing_dir);
+		return true;
+	}
+
+	/*
+         * If tracefs is not found (e.g., older kernel), try to find debugfs
+         * and use its subdirectory `tracing` as `TRACING_DIR`.
+         */
```
Comment (namhyung) [inline utils/mountinfo.c:53]: This doesn't follow the coding style.  Please do not indent the comment like this.

File: utils/mountinfo.h [hunk 2]
```diff
@@ -0,0 +1,13 @@
+#ifndef UFTRACE_MOUNT_INFO_H
+#define UFTRACE_MOUNT_INFO_H
+
+#include <stdbool.h>
+
+/* TODO: Okay to use `self`? */
+#define PROC_MOUNTINFO "/proc/self/mountinfo"
```
Comment (namhyung) [inline utils/mountinfo.h:7]: I think it's ok.

File: utils/mountinfo.c [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+	size_t len;
+	int i;
+
+	fp = fopen(PROC_MOUNTINFO, "r");
+	if (fp == NULL)
+		return false;
+
+	/* First, try to find tracefs. */
+	while (getline(&line, &len, fp) > 0) {
+		if (!(ptr = strstr(line, "tracefs")))
```
Comment (namhyung) [inline utils/mountinfo.c:20]: While this would work in most cases, it might not work properly if any other mount path contains the "tracefs".  You'd better use `sscanf()` to parse the mountinfo format properly - i.e. checking 9th position specifically.

**Review by namhyung — COMMENTED** [review]
Thanks for the contribution.  I have no preference on it but /proc/PID/mountinfo is available from 2.6.26 kernel which is ancient so no worry for compatibility.

Also I think we can move more tracefs utilities to the new file like get/put/open_tracing_file and write/append_tracing_file.  It could be named as utils/tracefs.[ch].

**Review by namhyung — DISMISSED** [review]
LGTM.

I suggest a follow up work to move `write_tracing_file()` (and `append_tracing_file()` too) to the utils/tracefs.c and use it in libmcount/misc.c.

**Comment by namhyung** [comment]
It'd be nice if you could add it to this PR.

File: utils/tracefs.h [hunk 4]
```diff
@@ -2,9 +2,30 @@
 #define UFTRACE_TRACEFS_H
 
 #include <stdbool.h>
+#include <stddef.h>
+#include <unistd.h>
 
 #define PROC_MOUNTINFO "/proc/self/mountinfo"
 
-bool find_tracing_dir(char **tracing_dir);
+bool find_tracing_dir(void);
```
Comment (namhyung) [inline utils/tracefs.h:10]: It doesn't need to be exposed, right?

File: libmcount/misc.c [hunk 5]
```diff
@@ -13,54 +13,23 @@
...
-	}
-
 	snprintf(buf, sizeof(buf), "%d", tid);
-	len = strlen(buf);
-	if (write(fd, buf, len) != len)
-		pr_dbg("update kernel event pid filter failed\n");
-
-	close(fd);
+	if (append_tracing_file("set_event_pid", buf) < 0)
+		pr_dbg("write to kernel event pid filter failed\n");
```
Comment (namhyung) [inline libmcount/misc.c:32]: Can we just call `set_tracing_pid()` here?  But it could be a separate change.

**Review by namhyung — COMMENTED** [review]
I think you are doing too many things in a single commit.  Let's break the second commit into parts:
* just move basic open/write
* convert libmcount/misc.c to use the functions
* introduce read_tracing_file() and use it

File: libmcount/misc.c [hunk 6]
```diff
@@ -16,46 +16,20 @@
...
-	}
-
-	snprintf(buf, sizeof(buf), "%d", tid);
-	len = strlen(buf);
-	if (write(fd, buf, len) != len)
-		pr_dbg("update kernel event pid filter failed\n");
-
-	close(fd);
+	if (append_tracing_file("set_event_pid", buf) < 0)
+		pr_dbg("write to kernel ftrace pid filter failed\n");
```
Comment (namhyung) [inline libmcount/misc.c:32]: Can we simply call `set_tracing_pid()`?

File: utils/kernel.c [hunk 7]
```diff
@@ -895,23 +895,23 @@ static int load_current_kernel(struct uftrace_kernel_reader *kernel)
...
+	fd = open_tracing_file("events/ftrace/funcgraph_entry/format", O_RDONLY);
 	if (fd < 0)
 		return -1;
 
 	len = read(fd, buf, sizeof(buf));
 	pevent_parse_event(pevent, buf, len, "ftrace");
 	close(fd);
 
-	fd = open_tracing_file("/events/ftrace/funcgraph_exit/format", O_RDONLY);
+	fd = open_tracing_file("events/ftrace/funcgraph_exit/format", O_RDONLY);
```
Comment (namhyung) [inline utils/kernel.c:914]: I think these should be squashed to the first commit.

File: libmcount/misc.c (hunk 6 above)
Comment (namhyung) [reply libmcount/misc.c:32]: Ah, ok.  Let's keep it for now. I think we can add `append_tracing_pid()`.

**Review by namhyung — APPROVED** [review]
LGTM, thanks a lot!

**Comment by namhyung** [comment]
Could you please rebase your branch on to the current master?
